### ISSUE TITLE
disp.yaml wrong symbol and mass

### ISSUE THREAD

**Issue by baranas** [atztogo/phonopy#36]
Hi, Togo

I am using your software for defect vibrational spectrum calculations (pwscf and vasp).
For my calculations I am using your FORCE_CONSTANTS file and displ.yaml. 
It is awesome :). On pwscf it works fine, however for vasp displ.yaml it mixes atomic 
symbols and masses.

For diamond
POTCAR

    PAW_PBE C 08Apr2002
    4.00000000000000000 
    ...

POSCAR

```
diamond 
    3.5620940727273465
      1.00 0.00 0.00
      0.00 1.00 0.00
      0.00 0.00 1.00
8
Direct
    0.000000000    0.000000000    0.000000000
    0.500000000    0.500000000    0.000000000
    0.000000000    0.500000000    0.500000000
    0.500000000    0.000000000    0.500000000
    0.250000000    0.250000000    0.250000000
    0.750000000    0.750000000    0.250000000
    0.750000000    0.250000000    0.750000000
    0.250000000    0.750000000    0.750000000    
```

It generates disp.yaml

```
natom:  216
displacements:
- atom:    1
  direction:
    [   1.0000000000000000,  0.0000000000000000,  0.0000000000000000 ]
  displacement:
    [   0.0100000000000000,  0.0000000000000000,  0.0000000000000000 ]
- atom:    1
  direction:
    [  -1.0000000000000000,  0.0000000000000000,  0.0000000000000000 ]
  displacement:
    [  -0.0100000000000000,  0.0000000000000000,  0.0000000000000000 ]
lattice:
- [    10.686282218182040,     0.000000000000000,     0.000000000000000 ] # a
- [     0.000000000000000,    10.686282218182040,     0.000000000000000 ] # b
- [     0.000000000000000,     0.000000000000000,    10.686282218182040 ] # c
points:
- symbol: H  # 1
  coordinates: [  0.000000000000000,  0.000000000000000,  0.000000000000000 ]
  mass: 1.007940
- symbol: H  # 2
  coordinates: [  0.333333333333333,  0.000000000000000,  0.000000000000000 ]
  mass: 1.007940                                 
...
```

with symbols H and masses 1.007940. I can overcome this in my software,
but in future it would be nice if you could fix that. By the way is it possible to contribute
to your code, I would like to optimise fc_symmetry which is very usefull for me.
Again thanks for such nice and usefull package.
