### ISSUE TITLE
invalid yaml output from --symmetry

### ISSUE THREAD

**Issue by ExpHP** [atztogo/phonopy#42]
A colleague found that `--symmetry` output cannot be read as YAML, because it is missing a closing brace on `translation`:

```yaml
space_group_operations:
- rotation: # 1
  - [ 1,  0 , 0]
  - [ 0,  1 , 0]
  - [ 0,  0 , 1]
  translation: [ 0.00000,  0.00000,  0.00000       # <-- invalid yaml
```

Also, it would seem that `point_group_type` and `site_point_group` should maybe be wrapped in quotes, so that they are always strings.

```yaml
# current output
site_point_group: 3m   # this is a string
site_point_group: 1    # this is an integer

# quoted output
site_point_group: '3m' # this is a string
site_point_group: '1'  # this is a string
```

Tested on `develop` (15c9c62) and `master` (2052ae2).
